---
 - hosts: all
   become:  yes 
   tasks: 
   - name :  "update apt packages"
     apt:
       update_cache: yes 
#node js specific settings
# installed from details 
#"https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04"

 - hosts: app
   become: all 
   vars:
     folderpath: /home/anisble/nodesetup
     appserverport: 8080
   tasks: 
   - name: "creating nodesetup directory"
     file:
      path: "{{ folderpath }}"
      state: directory
      mode: 0755
   - name: "download node js setup packages"
     command: "curl -sL https://deb.nodesource.com/setup_8.x -o {{ folderpath }}/nodesource_setup.sh"
   - name: "Exeucute dowbload shell script"
     command: "sudo bash {{ folderpath }}/nodesource_setup.sh"
   - name: "Install node js"
     apt:
       name: nodejs
       state: present 
   - name: " copy the templete"
     template:
       src: "templates/hello.js.j2"
       dest: "{{ folderpath }}/hello.js"

 - hosts: web 
   become: yes 
   vars:
     webserver_dns_name: "ec2-13-59-216-107.us-east-2.compute.amazonaws.com"
     appserver_ip: 172.31.46.55
   tasks:
   - name: "intall nginx"
     apt:
       name: nginx 
       status: present 
   - name: " copy the templete"
     template:
       src: "templates/default.j2"
       dest: /etc/nginx/sites-available/default
       notify: Restart Nginx 
   - name: Restart nginx
     service:
       name: nginx
       state: restarted
   
